name: Pipeline for Specie List Microservice

on:
  push:
    branches:
      - Production
    paths:
      - 'specie-list-service/**'
      - '.github/workflows/specie-list-pipeline.yml'
  pull_request:
    branches: 
      - Production
    paths:
      - 'specie-list-service/**'
      - '.github/workflows/specie-list-pipeline.yml'
jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker buildx build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_SPECIE_LIST }}:latest ./specie-list-service

      - name: Push Docker image to Dockerhub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_SPECIE_LIST }}:latest

  deploy-to-ec2-instance:
    needs: build-and-push-docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST_TEST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            echo "Pull, stop, and redeploy the Docker container"
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_SPECIE_LIST }}:latest
            docker stop ${{ secrets.DOCKER_IMAGE_SPECIE_LIST }} || true
            docker rm ${{ secrets.DOCKER_IMAGE_SPECIE_LIST }} || true
            docker run --restart always -e MONGO_URI=${{ secrets.MONGO_URI }} \
                       -e DB_NAME=${{ secrets.DB_NAME }} \
                       -e PORT_LIST=${{ secrets.PORT_LIST }} \
                       -d --name ${{ secrets.DOCKER_IMAGE_SPECIE_LIST }} \
                       -p ${{ secrets.PORT_LIST }}:${{ secrets.PORT_LIST }} ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_SPECIE_LIST }}:latest
